[tool.pytest.ini_options]
markers = [
    "parser: Parser strategy tests",
    "extractor: Extractor strategy tests",
    "enricher: Enricher strategy tests",
    "integration: Full pipeline integration tests",
    "slow: Tests that take >1 second",
]

addopts = [
    "-v",                    # Verbose output
    "--tb=short",           # Shorter tracebacks
    "--strict-markers",     # Fail on typo in marker names
    "-ra",                  # Show summary of all test outcomes
]

testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
